Importing the Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [ ]:
data=pd.read_csv('Grade_Predictor_Data.csv')
X=data.iloc[:,1:4].values

In [ ]:
int_features=[65,70,11,4]
y=int_features.pop()
features=np.array(int_features)

In [ ]:
print(features.reshape(1,-1))

[[65 70 11]]


In [ ]:
Y=data.iloc[:,y].values
print(Y)

[80 83 86 80 85 86 85 90 80 82 94 84 93 85 86 82 87 85 87 88 93 97]


Splitting into Training and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=0)

Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
print(X_train)

Decision Tree Regressor

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=500,random_state=0)
regressor.fit(X_train,Y_train)


RandomForestRegressor(n_estimators=500, random_state=0)

In [ ]:
#print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

New Predictions

In [ ]:
regressor.predict(sc.transform(features.reshape(1,-1)))

array([85.708])

Score test

In [ ]:
#from sklearn.metrics import r2_score
#print(r2_score(Y_test,y_pred))